OLD/ror/config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :sources

end

OLD/ror/app/models/news.rb
class News < ActiveRecord::Base
end

OLD/ror/app/models/source.rb
class Source < ActiveRecord::Base
end

OLD/ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

OLD/ror/app/controllers/news_controller.rb
# coding: utf-8
class NewsController < ApplicationController
    before_action :set_news, only: [:show, :edit, :update, :destroy]

    # GET /news
    # GET /news.json
    def index
        if params.has_key?(:date)
            #  @news = News.where(:date=>((Date.today-1).beginning_of_day..Date.today.end_of_day))
            date = Date.strptime(params[:date],"%Y%m%d")
            @news = News.where(:date=>(date.beginning_of_day..date.end_of_day))
        else
            @news = News.where(:date=>(Date.today.beginning_of_day..Date.today.end_of_day)).order(date: :desc)
            #@news = News.where(:date=>(Date.today.beginning_of_day..Date.today.end_of_day))
            #  @news = News.all
        end
        #@news.select(:title,:link,:date,:source,:image_link,:url)
    end

    # GET /news/1
    # GET /news/1.json
    def show
    end

    # GET /news/new
    def new
        @news = News.new
    end

    # GET /news/1/edit
    def edit
    end

    # POST /news
    # POST /news.json
    def create
        news_params[:date]=Date.parse(news_params[:date])
        logger.fatal news_params
        @news = News.new(news_params)
        logger.debug @news.guid
        if News.exists?(:guid => @news.guid)
            #logger.debug "Exists already" 
            render plain: "Exists Already - " + @news.title
        else
            respond_to do |format|
                if @news.save
                    format.html { redirect_to @news, notice: 'News was successfully created.' }
                    format.json { render :show, status: :created, location: @news }
                else
                    format.html { render :new }
                    format.json { render json: @news.errors, status: :unprocessable_entity }
                end
            end
        end
    end

    # PATCH/PUT /news/1
    # PATCH/PUT /news/1.json
    def update
        respond_to do |format|
            if @news.update(news_params)
                format.html { redirect_to @news, notice: 'News was successfully updated.' }
                format.json { render :show, status: :ok, location: @news }
            else
                format.html { render :edit }
                format.json { render json: @news.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /news/1
    # DELETE /news/1.json
    def destroy
        @news.destroy
        respond_to do |format|
            format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
        @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
        params.require(:news).permit(:title, :guid, :link, :date, :source, :image_link, :description)
    end
end

OLD/ror/app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:name, :display, :language, :rss_url)
    end
end

OLD/ror/app/helpers/application_helper.rb
module ApplicationHelper
end

OLD/ror/app/helpers/news_helper.rb
module NewsHelper
end

OLD/ror/app/helpers/sources_helper.rb
module SourcesHelper
end

OLD/ror/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ror</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

OLD/ror/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/ror/app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

OLD/ror/app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Guid</th>
      <th>Link</th>
      <th>Date</th>
      <th>Source</th>
      <th>Image link</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.guid %></td>
        <td><%= news.link %></td>
        <td><%= news.date %></td>
        <td><%= news.source %></td>
        <td><%= news.image_link %></td>
        <td><%= news.description %></td>
        <td><%= link_to 'Show', news %></td>
<!--
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
-->
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
<%= link_to 'New News', new_news_path %>
-->

OLD/ror/app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

OLD/ror/app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @news.guid %>
</p>

<p>
  <strong>Link:</strong>
  <%= @news.link %>
</p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<p>
  <strong>Source:</strong>
  <%= @news.source %>
</p>

<p>
  <strong>Image link:</strong>
  <%= @news.image_link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>
<!--
<%= link_to 'Edit', edit_news_path(@news) %> |
-->
<%= link_to 'Back', news_index_path %>

OLD/ror/app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.check_box :display %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :rss_url %><br>
    <%= f.text_field :rss_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/ror/app/views/sources/edit.html.erb
<h1>Editing Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

OLD/ror/app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Display</th>
      <th>Language</th>
      <th>Rss url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.name %></td>
        <td><%= source.display %></td>
        <td><%= source.language %></td>
        <td><%= source.rss_url %></td>
        <td><%= link_to 'Show', source %></td>
<!--
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
<%= link_to 'New Source', new_source_path %>
-->

OLD/ror/app/views/sources/new.html.erb
<h1>New Source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

OLD/ror/app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @source.name %>
</p>

<p>
  <strong>Display:</strong>
  <%= @source.display %>
</p>

<p>
  <strong>Language:</strong>
  <%= @source.language %>
</p>

<p>
  <strong>Rss url:</strong>
  <%= @source.rss_url %>
</p>
<!--
<%= link_to 'Edit', edit_source_path(@source) %> |
-->
<%= link_to 'Back', sources_path %>